.PHONY: clean All

All:
	@echo "----------Building project:[ RCBot2Meta - Release_NonHomeFolder_Win32 ]----------"
	@"$(MAKE)" -f  "RCBot2Meta.mk"
clean:
	@echo "----------Cleaning project:[ RCBot2Meta - Release_NonHomeFolder_Win32 ]----------"
	@"$(MAKE)" -f  "RCBot2Meta.mk" clean
